Add Auth backend
Nitrokey/nitrokey-3-firmware pull request #186
Opened 2023-03-03 13:19 UTC by sosthene-nitrokey

2023-03-03 14:53 UTC, sosthene-nitrokey commented
The `lpc55-hal` crate is missing support for the `PUF` so we cannot use it (for now).
The solution will be to update it. Starting point:

This struct doesn't have a PUF: https://docs.rs/lpc55-hal/latest/lpc55_hal/struct.Peripherals.html

This one has: https://docs.rs/lpc55-pac/latest/lpc55_pac/struct.Peripherals.html

So the PUF peripheral is lost [here](https://github.com/Nitrokey/nitrokey-3-firmware/blob/main/runners/embedded/src/soc_lpc55/mod.rs#L32) in the conversion.


The PUF is a bit more complex than the ER in the nrf. It first needs to be `enrolled`, which generates a 1192 "activation code that needs to be stored in the flash". Then a key needs to be generated, and the key code (52 bytes for 256 bits I think) needs to be stored too. 

Then using the same activation code and key code the key can be extracted.

It would actually be more secure to not extract and use the PUF key to encrypt the PIN to make extraction of data for offline attacks impossible.

2023-03-03 15:05 UTC, sosthene-nitrokey commented
Relevant PR: https://github.com/lpc55/lpc55-hal/pull/61

2023-03-07 15:34 UTC, robin-nitrokey requested changes

2023-03-07 15:34 UTC, robin-nitrokey commented on Cargo.toml
> +lpc55-hal = { git = "https://github.com/robin-nitrokey/lpc55-hal", rev = "f49c9abaa3ef6805d265f7cda3fe1920c3a53aad" }
Please create a tag in our fork for `lpc55-hal`.

2023-03-07 15:37 UTC, sosthene-nitrokey commented on Cargo.toml
> +lpc55-hal = { git = "https://github.com/robin-nitrokey/lpc55-hal", rev = "f49c9abaa3ef6805d265f7cda3fe1920c3a53aad" }
I don't have write access to it

2023-03-07 16:07 UTC, robin-nitrokey commented on Cargo.toml
> +lpc55-hal = { git = "https://github.com/robin-nitrokey/lpc55-hal", rev = "f49c9abaa3ef6805d265f7cda3fe1920c3a53aad" }
AFAIS the tag does not include the `status` and `allow` methods.

2023-03-10 18:17 UTC, robin-nitrokey commented
I think this one should be ready to merge once we drop the lpc55-specific changes.

2023-03-13 08:42 UTC, sosthene-nitrokey commented
Which changes should we drop? To me the current changes are what we want no?

2023-03-13 08:58 UTC, robin-nitrokey commented
Didn’t we decide to not use a hardware key on the LPC55 and instead reserve the PUF for future use?

2023-03-13 09:18 UTC, robin-nitrokey approved these changes

2023-03-13 09:52 UTC, merged