Update Secrets App to v0.10
Nitrokey/nitrokey-3-firmware pull request #246
Opened 2023-04-22 17:30 UTC by szszszsz

Update Secrets App to v0.10

Will be corrected to the proper version after the review and release.
Depends on:
- https://github.com/Nitrokey/trussed-secrets-app/pull/53

2023-04-23 07:59 UTC, robin-nitrokey requested changes

2023-04-23 07:59 UTC, robin-nitrokey commented on components/apps/src/lib.rs
> +        let mut options = oath_authenticator::Options::new(Location::External, 0, 1);
We should use the `CustomStatus` enum here instead of hardcoding the values.  Suggested change:  https://github.com/Nitrokey/nitrokey-3-firmware/commit/bede2d48dc004c5235cb483ab6aac3ff2d4fb56b

2023-04-24 09:24 UTC, szszszsz commented on components/apps/src/lib.rs
> +        let mut options = oath_authenticator::Options::new(Location::External, 0, 1);
Yup, that refactoring looks good - merged in!

2023-04-26 11:15 UTC, szszszsz commented
Somehow. Cargo.toml got removed during the rebased process. Looking into it.

2023-04-26 11:20 UTC, szszszsz commented
This should work now. Ready for review.

2023-04-26 11:44 UTC, robin-nitrokey approved these changes
Looks good, thank you!

2023-04-26 12:28 UTC, merged