Fix embedded runner always recompiling
Nitrokey/nitrokey-3-firmware pull request #265
Opened 2023-05-11 13:09 UTC by sosthene-nitrokey

Cargo recompiles (and reruns the build.rs) if the cfg.toml file has been modified Previously all calls to make rewrote this file and thus caused unneccessary recompilation. This patch adds a check that the contents of the file should actually be modified before rewriting it.

2023-05-11 17:58 UTC, szszszsz requested changes
Is `mv` foolproof here?

2023-05-11 17:58 UTC, szszszsz commented on runners/embedded/create_cfg.sh
> +  echo "eitasurteeeee"
Debug message? :>
Please remove or replace with English words.

2023-05-11 17:58 UTC, szszszsz commented on runners/embedded/create_cfg.sh
> +  mv $TMP_CFG cfg.toml
Won't `mv` fail on overwrite attempt by default?

2023-05-12 15:46 UTC, sosthene-nitrokey commented on runners/embedded/create_cfg.sh
> +  echo "eitasurteeeee"
Yes this was for debugging. Removed

2023-05-12 15:46 UTC, sosthene-nitrokey commented on runners/embedded/create_cfg.sh
> +  mv $TMP_CFG cfg.toml
Good catch. I added it

2023-05-15 09:41 UTC, daringer approved these changes

2023-06-22 12:07 UTC, robin-nitrokey approved these changes

2023-06-28 07:41 UTC, sosthene-nitrokey commented
> Looks good. I would remove all other `-f` switches though, since we do not expect any problems here, and would rather learn if something is blocking the operation for `cp` and `rm`.

The last `rm` failed indeed if the file had been moved. I put it in the `else` and removed the `-f` for the first, which was unnecessary.

2023-07-12 13:16 UTC, szszszsz commented
Merge?

2023-07-12 13:17 UTC, merged