Add Nitrokey WebCrypt
Nitrokey/nitrokey-3-firmware pull request #294
Opened 2023-06-20 14:17 UTC by szszszsz

Add Nitrokey WebCrypt application

2023-06-20 14:38 UTC, szszszsz commented
Flashes, runs and status command works. Not all commands are working though - working on that.

2023-06-20 19:50 UTC, robin-nitrokey requested changes

2023-06-20 19:50 UTC, robin-nitrokey commented on components/apps/src/lib.rs
> +            BackendId::Custom(Backend::SoftwareRsa),
Does it really need RSA?  Can’t find it in the app source.  If it does, it should also activate the `backend-rsa` feature.

2023-06-21 08:09 UTC, sosthene-nitrokey commented
There will probably need to be a bit of rebasing to be done to make it compatible #272

2023-06-21 11:20 UTC, szszszsz commented on components/apps/src/lib.rs
> +            BackendId::Custom(Backend::SoftwareRsa),
Good spot! Will check that one out.
Yes, RSA is used, and tested against test suite, though still WIP (not merged to main branch, and here the WIP branch was used directly).

2023-06-22 11:02 UTC, szszszsz commented
1. Moved to cancel-supporting update. Builds. 
2. Currently can crash due to stack overflow on some Webcrypt calls during deserialization, especially when used with PIV. Should be safe to use otherwise.
3. Uses internal filesystem (to be corrected).
4. Can't be merged yet, as it uses side branches with new features.
```
# Required for inject-any-key and hmacsha256p256
trussed = { git = "https://github.com/Nitrokey/trussed", branch = "webcrypt-devel-0.1.0-nk12" }
# Enable this for FIDO2 transport support
ctaphid-dispatch = { git = "https://github.com/Nitrokey/ctaphid-dispatch.git", branch="multiple_apps" }
```

2023-06-22 12:01 UTC, robin-nitrokey commented on components/apps/Cargo.toml
> +webcrypt = ["dep:webcrypt", "backend-auth"]
Should also require `backend-rsa`.

2023-06-22 12:03 UTC, szszszsz commented on components/apps/Cargo.toml
> +webcrypt = ["dep:webcrypt", "backend-auth"]
Weird. It got eaten during rebase I guess. Good you have checked that one again.
Corrected.

2023-06-22 12:06 UTC, robin-nitrokey reviewed
Looks good so far.  Regarding the integration, I think only the PRs and eventually tags for the Git dependencies are missing.

2023-06-30 16:06 UTC, szszszsz commented
1. Does not crash anymore on NK3AM with the recent Webcrypt release. Works with https://webcrypt.nitrokey.com/ as well.
2. Still uses internal filesystem, but that can be handled in the next PR.
3. No side branches are used anymore, except for the `trussed-staging` backend and Webcrypt itself. Both will be corrected in the next steps.
4. The new extension added to the `trussed-staging` needs to be activated by feature, so it should be transparent for non-test build.

2023-06-30 16:22 UTC, szszszsz commented
Just BTW, for some reason flexiber patch is not used:
```
warning: Patch `flexiber v0.1.1 (https://github.com/Nitrokey/flexiber?tag=0.1.1.nitrokey#26f2c804)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```

2023-06-30 16:43 UTC, szszszsz commented
I've just noticed that it breaks on the "fat" LTO setting. Can we use "thin" for now?

2023-06-30 17:27 UTC, robin-nitrokey commented
> Just BTW, for some reason flexiber patch is not used:

We use flexiber 0.1.0 but your patch points to 0.1.1.  In order to use it, you have to run `cargo update -p flexiber`.

2023-07-03 17:37 UTC, szszszsz commented
1. Moved to EFS
2. Still crashes with `LTO=true`, even with buffer and max field width to 600 bytes. I have added `#[inline(never)]` in multiple places, but this did not solve it.

2023-07-04 11:58 UTC, daringer approved these changes

2023-07-04 11:58 UTC, daringer approved these changes

2023-07-04 15:29 UTC, szszszsz commented
Will be merged soon after a proper WebCrypt release is done.

2023-07-04 16:33 UTC, szszszsz commented
All ticks green, merging

2023-07-04 16:33 UTC, merged