Use updated apdu-dispatch and dependencies
Nitrokey/nitrokey-3-firmware pull request #376
Opened 2023-11-08 15:26 UTC by sosthene-nitrokey

Depends on:

- https://github.com/Nitrokey/nitrokey-websmartcard-rust/pull/11
- https://github.com/Nitrokey/trussed-secrets-app/pull/104
- https://github.com/Nitrokey/piv-authenticator/pull/39
- https://github.com/Nitrokey/opcard-rs/pull/184
- https://github.com/Nitrokey/admin-app/pull/14
- https://github.com/Nitrokey/fido-authenticator/pull/40

2023-11-08 15:35 UTC, sosthene-nitrokey commented
This would fix #301

2023-11-08 15:40 UTC, robin-nitrokey requested changes
- As this will probably be the last change before the release, I vote for merging and tagging the app PRs before merging this PR.
- Please add the changed behavior (at least for opcard?) to the changelog.

2023-11-10 11:31 UTC, robin-nitrokey approved these changes

2023-11-10 11:31 UTC, robin-nitrokey commented on Cargo.toml
>  usbd-ccid = { git = "https://github.com/Nitrokey/usbd-ccid", tag = "v0.2.0-nitrokey.1" }
For these unreleased upstream changes, commits from the main branch would also be fine for me because we don’t force-push there.  For forked or unreleased crates, the risk is much higher that we lose the commit at some point in the future.  But of course tagging doesn’t hurt.

2023-11-10 12:24 UTC, merged