Refactor Soc trait, part II (storage)
Nitrokey/nitrokey-3-firmware pull request #419
Opened 2023-12-20 16:43 UTC by robin-nitrokey

This is a follow-up to:
- https://github.com/Nitrokey/nitrokey-3-firmware/pull/412

It makes the store implementation generic over the `Soc` implementation, meaning that we no longer use any `Soc as SocT` typedef constructs and that the library part of the embedded runner is fully generic over the `Soc`.  This also makes the storage initialization much easier to read, partly by moving the Soc-specific code like the NRF52 IFS migration out of the common implementation and into the soc module.

The downside is that the `static mut`s holding the storage components need concrete types and cannot be defined using generics, so they have to be provided by every `Soc` implementation.  I introduced a helper trait and a macro so it is not necessary to manually write the required boilerplate code.

I also tested a much nicer implementation using a single struct that gathers all statics used for storage and provides nice and safe(r) abstractions around them.   Unfortunately, it significantly increased binary size by several hundred bytes so I decided to stick with the plain `static mut`s for the time being.

2023-12-20 17:10 UTC, sosthene-nitrokey requested changes

2023-12-20 17:10 UTC, sosthene-nitrokey commented on runners/embedded/src/store.rs
> +            error!("VFS Mount Error {:?}", _e);
This fails to compile with logs enabled.

2023-12-20 17:19 UTC, robin-nitrokey commented on runners/embedded/src/store.rs
> +            error!("VFS Mount Error {:?}", _e);
Good catch, fixed.  Also reduces binary size for some reason …

2023-12-21 09:12 UTC, sosthene-nitrokey approved these changes

2023-12-21 16:12 UTC, daringer approved these changes

2024-01-04 21:03 UTC, merged