Improve hacker setup instructions
Nitrokey/nitrokey-3-firmware pull request #527
Opened 2024-08-24 12:16 UTC by enrikb

Two small additions I stumbled accross when commissioning my new Nitrokey 3 (Hacker).

2025-02-13 13:41 UTC, daringer approved these changes

2025-02-13 20:19 UTC, robin-nitrokey requested changes
Thanks for the PR!  I just have one comment regarding the udev rules.

2025-02-13 20:19 UTC, robin-nitrokey commented on 70-lpc55.rules
Please move the file to the `utils/lpc55-builder` directory and mention it in the relevant section of the quickstart guide:

https://github.com/Nitrokey/nitrokey-3-firmware/blob/e2774d30cd4972480d865d609525550688c5e9d8/docs/lpc55-quickstart.md?plain=1#L79

2025-02-15 18:31 UTC, enrikb commented on 70-lpc55.rules
I pushed a suggested fixup to address your comment. I also tried to fix the NXP link, as it seems to have changed. Please let me know if this matches your expectations.

Of course, I'm planning to squash the changes when final. Thanks!

2025-02-16 17:23 UTC, robin-nitrokey commented on 70-lpc55.rules
Great, thank you!

2025-02-16 17:23 UTC, robin-nitrokey approved these changes

2025-02-17 11:25 UTC, enrikb commented
Sqashed and rebased on current `main`.

2025-02-17 14:11 UTC, merged

2025-02-17 14:11 UTC, robin-nitrokey commented
Merged, thank you!