Update icon for fido2 mds
Nitrokey/nitrokey-3-firmware pull request #555
Opened 2024-10-30 14:17 UTC by daringer

* update icon to be a svg
* re-create all mds jsons `v5`

2024-10-30 14:44 UTC, sosthene-nitrokey approved these changes

2024-10-30 14:44 UTC, sosthene-nitrokey commented on utils/fido2-mds/generate-mds.py
> +            options["credentialMgmtPreview"] = (True,)
Why the one-element tuple?

2024-10-30 16:04 UTC, robin-nitrokey requested changes

2024-10-30 16:04 UTC, robin-nitrokey commented on utils/fido2-mds/generate-mds.py
> +            icon = f"data:image/svg+xml;base64,{icon_base64}"
The spec says:

> icon, of type [DOMString](https://heycam.github.io/webidl/#idl-DOMString)

>    A data: url [[RFC2397]](https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html#biblio-rfc2397) encoded [[PNG]](https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html#biblio-png) icon for the Authenticator.

https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html#dom-metadatastatement-icon

2024-10-31 10:17 UTC, daringer commented on utils/fido2-mds/generate-mds.py
> +            options["credentialMgmtPreview"] = (True,)
uh good catch, accidental `,` added

2024-10-31 10:28 UTC, daringer commented on utils/fido2-mds/generate-mds.py
> +            icon = f"data:image/svg+xml;base64,{icon_base64}"
uh, ok, the mymds portal seems to be just fine with the svg, but spec-conformance is for sure better

2024-10-31 10:31 UTC, daringer commented on utils/fido2-mds/generate-mds.py
> +            options["credentialMgmtPreview"] = (True,)
done

2024-10-31 10:33 UTC, robin-nitrokey approved these changes

2024-10-31 12:34 UTC, merged