Simplify VFS initialization
Nitrokey/nitrokey-3-firmware pull request #569
Opened 2024-12-09 10:57 UTC by sosthene-nitrokey

Can be improved further once https://github.com/trussed-dev/littlefs2/pull/87 is merged.

2024-12-09 11:01 UTC, robin-nitrokey requested changes

2024-12-09 11:01 UTC, robin-nitrokey commented on components/boards/src/store.rs
> +    };
Why not `VolatileStorage::new()`?

2024-12-09 14:57 UTC, robin-nitrokey approved these changes

2024-12-10 10:28 UTC, robin-nitrokey commented
Note sure what causes the binary size change.  I cannot reproduce it locally.

2024-12-10 10:28 UTC, sosthene-nitrokey commented
I do not understand the size increase. On the opposite I would have expected a size decrease.

2024-12-10 10:48 UTC, robin-nitrokey commented
My first guess was that maybe the build environment changed and caused the size change, but running the CI for a no-op PR like https://github.com/Nitrokey/nitrokey-3-firmware/pull/240 does not cause a size difference.

2024-12-10 10:54 UTC, sosthene-nitrokey commented
I can reproduce the size change locally.  My first thought was a missing rebase but it's not that.

2024-12-10 11:33 UTC, robin-nitrokey commented
I only checked the output of `make bloat` locally, not of the binary size.  It is quite the coincidence that the volatile storage size is 8192 and the size change is e. g. 8176.  It looks like this is just the size of the initializer?  Using a `MaybeUninit` to defer initialization to runtime could help.

2024-12-10 12:53 UTC, sosthene-nitrokey commented
Yes it looks like it was that. It's including the full zeros of the static? That's not good. As a result using `MaybeUninit` improves the binary size by the couple of relevant bytes.

2024-12-10 13:08 UTC, robin-nitrokey approved these changes

2024-12-13 17:06 UTC, daringer approved these changes

2024-12-13 17:07 UTC, daringer commented
mmmh, falsely approved although the build fails - didn't check it yet

2024-12-16 09:46 UTC, merged